// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVroAuxgCJADoe6Uu7rBxgsx24yJuVF9U',
    appId: '1:521735339162:web:561fd0f5bcfaf804b3f323',
    messagingSenderId: '521735339162',
    projectId: 'moviemetric-644f9',
    authDomain: 'moviemetric-644f9.firebaseapp.com',
    databaseURL: 'https://moviemetric-644f9-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'moviemetric-644f9.appspot.com',
    measurementId: 'G-M84WFTJSZL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2tzRIm_nMahXWnkQKA6q6t5ewp41PdTM',
    appId: '1:521735339162:android:d7f772bc93d5f1fcb3f323',
    messagingSenderId: '521735339162',
    projectId: 'moviemetric-644f9',
    databaseURL: 'https://moviemetric-644f9-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'moviemetric-644f9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyVKmoM-efPQdcO6cYKzqQHYQboOYsNSA',
    appId: '1:521735339162:ios:c96296e1e04477f7b3f323',
    messagingSenderId: '521735339162',
    projectId: 'moviemetric-644f9',
    databaseURL: 'https://moviemetric-644f9-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'moviemetric-644f9.appspot.com',
    iosClientId: '521735339162-guql0vaikv5mvnshlqb1sh8vhcqmgtf3.apps.googleusercontent.com',
    iosBundleId: 'fe.up.pt.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyVKmoM-efPQdcO6cYKzqQHYQboOYsNSA',
    appId: '1:521735339162:ios:c96296e1e04477f7b3f323',
    messagingSenderId: '521735339162',
    projectId: 'moviemetric-644f9',
    databaseURL: 'https://moviemetric-644f9-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'moviemetric-644f9.appspot.com',
    iosClientId: '521735339162-guql0vaikv5mvnshlqb1sh8vhcqmgtf3.apps.googleusercontent.com',
    iosBundleId: 'fe.up.pt.app',
  );
}
